# permissions for end users to edit nodecleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-ncleaner
    app.kubernetes.io/managed-by: kustomize
  name: nodecleaner-editor-role
rules:
- apiGroups:
  - crd.norbinto
  resources:
  - nodecleaners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.norbinto
  resources:
  - nodecleaners/status
  verbs:
  - get
