# permissions for end users to view nodecleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-ncleaner
    app.kubernetes.io/managed-by: kustomize
  name: nodecleaner-viewer-role
rules:
- apiGroups:
  - crd.norbinto
  resources:
  - nodecleaners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.norbinto
  resources:
  - nodecleaners/status
  verbs:
  - get
